# Generated by Django 4.2.6 on 2023-10-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='department_user', to='project_management.user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_user', to='project_management.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_user', to='project_management.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_user', to='project_management.user'),
        ),
    ]
